
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T21:15:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a2e300170efc08cb509a0b4ff6248f8d55ae777",
 "version": "2.0.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
